# -*- coding: utf-8 -*-
"""P-300 SPELLER

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ejANqn-2N6U52I1U00xm6le4jk82Z7sW
"""

from google.colab import files
uploaded = files.upload()

pip install mne numpy scipy matplotlib scikit-learn pandas seaborn pyriemann

DATA_DIR = "/content/"
SUBJECTS  = ["S1", "S2", "S3", "S4", "S5"]
CH_NAMES  = ["Fz", "Cz", "P3", "Pz", "P4", "PO7", "PO8", "Oz"]

FS_TARGET  = 64
T_START    = 0.0
T_END      = 0.8
BP_LOW     = 0.5
BP_HIGH    = 30.0
BASELINE_S = 0.1
AMP_THRESH = 150.0  # tried 100 first —> lost too many epochs, 150 was the best.

N_XDAWN  = 4
N_FOLDS  = 5

print("Configuration READY!")

def load_subject(sid):
    path = os.path.join(DATA_DIR, f"{sid}.mat")
    mat  = sio.loadmat(path)
    fs   = float(np.squeeze(mat["fs"]))
    eeg  = mat["y"].astype(np.float64)
    trig = mat["trig"].flatten().astype(np.float64)
    return fs, eeg, trig


fs_demo, eeg_demo, trig_demo = load_subject("S1")

print(f"Sampling rate   : {fs_demo:.0f} Hz")
print(f"EEG shape       : {eeg_demo.shape}")
print(f"Trigger values  : {np.unique(trig_demo)}")
print(f"Target events   : {int((trig_demo == 1).sum())}")
print(f"Non-target evts : {int((trig_demo == -1).sum())}")

# S4 and S5 look cleaner than S1-S3 in terms of baseline noise

for sid in SUBJECTS:
    fs, eeg, trig = load_subject(sid)

    fig, axes = plt.subplots(8, 1, figsize=(14, 16), sharex=True)
    t_sec = np.arange(int(5 * fs)) / fs

    for ch, ax in enumerate(axes):
        ax.plot(t_sec, eeg[:int(5*fs), ch], lw=0.6, color="#2c3e50")
        ax.set_ylabel(CH_NAMES[ch], fontsize=9, rotation=0, labelpad=30)
        stim_times = np.where(np.diff((trig[:int(5*fs)] != 0).astype(int)) > 0)[0] / fs
        for t in stim_times:
            ax.axvline(t, color="#e74c3c", alpha=0.4, lw=0.8)

    axes[-1].set_xlabel("Time (s)")
    fig.suptitle(f"{sid} — Raw EEG (first 5s, red lines = stimulus onsets)",
                 fontsize=13, fontweight="bold")
    plt.tight_layout()
    plt.savefig(f"raw_eeg_{sid}.png", dpi=150, bbox_inches="tight")
    plt.show()
    print(f"Saved: raw_eeg_{sid}.png")

def bandpass_filter(eeg, low, high, fs, order=4):
    nyq  = fs / 2.0
    b, a = signal.butter(order, [low / nyq, high / nyq], btype="band")
    return signal.filtfilt(b, a, eeg, axis=0)


# tried MNE's FIR filter first.
# Butterworth + filtfilt was faster and still preserved the ERP shape!

eeg_filt = bandpass_filter(eeg_demo, BP_LOW, BP_HIGH, fs_demo)
print(f"Filtered EEG shape: {eeg_filt.shape}")

# filtering makes a noticeable difference on S3 and S5, less so on others

for sid in SUBJECTS:
    fs, eeg, trig = load_subject(sid)
    eeg_f = bandpass_filter(eeg, BP_LOW, BP_HIGH, fs)

    t_sec = np.arange(int(5 * fs)) / fs

    fig, axes = plt.subplots(8, 2, figsize=(16, 16), sharex=True)

    for ch in range(8):
        axes[ch, 0].plot(t_sec, eeg[:int(5*fs), ch], lw=0.6, color="#2c3e50")
        axes[ch, 0].set_ylabel(CH_NAMES[ch], fontsize=9, rotation=0, labelpad=30)
        axes[ch, 1].plot(t_sec, eeg_f[:int(5*fs), ch], lw=0.6, color="#e74c3c")

        if ch == 0:
            axes[ch, 0].set_title("Raw", fontsize=11, fontweight="bold")
            axes[ch, 1].set_title("Filtered (0.5-30 Hz)", fontsize=11, fontweight="bold")

    axes[-1, 0].set_xlabel("Time (s)")
    axes[-1, 1].set_xlabel("Time (s)")
    fig.suptitle(f"{sid} — Raw vs Filtered EEG", fontsize=13, fontweight="bold")
    plt.tight_layout()
    plt.savefig(f"raw_vs_filtered_{sid}.png", dpi=150, bbox_inches="tight")
    plt.show()
    print(f"Saved: raw_vs_filtered_{sid}.png")

def find_trigger_onsets(trig):
    onsets, labels = [], []
    prev = 0.0
    for i, val in enumerate(trig):
        if prev == 0.0 and val != 0.0:
            onsets.append(i)
            labels.append(1 if val > 0 else -1)
        prev = val
    return np.array(onsets, dtype=int), np.array(labels, dtype=int)


def extract_epochs(eeg, onsets, labels, fs, t_start=0.0, t_end=0.8):
    # started with -0.1 to 0.7 then switched to 0-0.8
    # For the first version, I used the first 100 ms of each epoch as a simple baseline.
    # A cleaner option would be using a pre-stimulus window!!!

    n0, n1 = int(t_start * fs), int(t_end * fs)
    N = eeg.shape[0]
    epochs, valid_labels = [], []
    for onset, lbl in zip(onsets, labels):
        s, e = onset + n0, onset + n1
        if 0 <= s and e <= N:
            epochs.append(eeg[s:e])
            valid_labels.append(lbl)
    return np.array(epochs), np.array(valid_labels)


onsets_demo, labels_demo = find_trigger_onsets(trig_demo)
epochs_raw, labels_demo  = extract_epochs(eeg_filt, onsets_demo, labels_demo,
                                           fs_demo, T_START, T_END)

print(f"Total epochs  : {epochs_raw.shape[0]}")
print(f"Epoch shape   : {epochs_raw.shape}")
print(f"Target        : {(labels_demo == 1).sum()}")
print(f"Non-target    : {(labels_demo == -1).sum()}")

def resample_epochs(epochs, fs_orig, fs_new):
    # downsampling to 64Hz — P300 peaks around 300ms -->>> 64Hz is ENOUGH!
    # reduces feature dimension ----> before classification
    n_trials, n_samp, n_ch = epochs.shape
    n_new = int(round(n_samp * fs_new / fs_orig))
    out   = np.zeros((n_trials, n_new, n_ch))
    for ch in range(n_ch):
        out[:, :, ch] = signal.resample(epochs[:, :, ch], n_new, axis=1)
    return out


epochs_ds = resample_epochs(epochs_raw, fs_demo, FS_TARGET)

print(f"Before resample : {epochs_raw.shape} @ {fs_demo:.0f} Hz")
print(f"After  resample : {epochs_ds.shape} @ {FS_TARGET} Hz")

# resampling from 250 to 64Hz — waveform shape is preserved, just fewer points
for sid in SUBJECTS:
    fs, eeg, trig = load_subject(sid)
    eeg_f = bandpass_filter(eeg, BP_LOW, BP_HIGH, fs)
    onsets, labels = find_trigger_onsets(trig)
    epochs, labels = extract_epochs(eeg_f, onsets, labels, fs, T_START, T_END)
    epochs_ds = resample_epochs(epochs, fs, FS_TARGET)

    tgt_idx = np.where(labels == 1)[0][0]

    t_orig = np.linspace(T_START, T_END, epochs.shape[1])
    t_ds   = np.linspace(T_START, T_END, epochs_ds.shape[1])

    fig, axes = plt.subplots(2, 4, figsize=(16, 8))
    axes = axes.flatten()

    for ch in range(8):
        axes[ch].plot(t_orig, epochs[tgt_idx, :, ch], color="#2c3e50", lw=1.5, label=f"250 Hz ({epochs.shape[1]} pts)")
        axes[ch].plot(t_ds, epochs_ds[tgt_idx, :, ch], color="#e74c3c", lw=1.5, ls="--", label=f"64 Hz ({epochs_ds.shape[1]} pts)")
        axes[ch].set_title(CH_NAMES[ch], fontsize=12, fontweight="bold")
        axes[ch].set_xlabel("Time (s)")
        axes[ch].set_ylabel("µV")
        axes[ch].grid(True, alpha=0.3)
        if ch == 0:
            axes[ch].legend(fontsize=9)

    fig.suptitle(f"{sid} — Before vs After Resample (single target epoch)", fontsize=14, fontweight="bold")
    plt.tight_layout()
    plt.savefig(f"resample_{sid}.png", dpi=150, bbox_inches="tight")
    plt.show()
    print(f"Saved: resample_{sid}.png")

# 100uV threshold removed too many target epochs, settled on 150uV

def reject_artifacts(epochs, labels, threshold=150.0):

    ptp  = (epochs.max(axis=1) - epochs.min(axis=1)).max(axis=1)
    mask = ptp < threshold
    return epochs[mask], labels[mask], int((~mask).sum())


for sid in SUBJECTS:
    fs, eeg, trig = load_subject(sid)
    eeg_f = bandpass_filter(eeg, BP_LOW, BP_HIGH, fs)
    onsets, labels = find_trigger_onsets(trig)
    epochs, labels = extract_epochs(eeg_f, onsets, labels, fs, T_START, T_END)
    epochs_ds = resample_epochs(epochs, fs, FS_TARGET)

    # baseline correction before rejection — otherwise DC offset inflates ptp
    n_base = int(BASELINE_S * FS_TARGET)
    baseline = epochs_ds[:, :n_base, :].mean(axis=1, keepdims=True)
    epochs_bl = epochs_ds - baseline

    epochs_clean, labels_clean, n_rem = reject_artifacts(epochs_bl, labels, AMP_THRESH)
    print(f"{sid}: {epochs_bl.shape[0]} → {epochs_clean.shape[0]} kept ({n_rem} removed)")

# visualizing which epochs were rejected helps verify the threshold was reasonable
for sid in SUBJECTS:
    fs, eeg, trig = load_subject(sid)
    eeg_f = bandpass_filter(eeg, BP_LOW, BP_HIGH, fs)
    onsets, labels = find_trigger_onsets(trig)
    epochs, labels = extract_epochs(eeg_f, onsets, labels, fs, T_START, T_END)
    epochs_ds = resample_epochs(epochs, fs, FS_TARGET)
    n_base = int(BASELINE_S * FS_TARGET)
    baseline = epochs_ds[:, :n_base, :].mean(axis=1, keepdims=True)
    epochs_bl = epochs_ds - baseline

    ptp = (epochs_bl.max(axis=1) - epochs_bl.min(axis=1)).max(axis=1)

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 4))

    # peak-to-peak distribution
    ax1.hist(ptp, bins=40, color="#3498db", edgecolor="white", alpha=0.8)
    ax1.axvline(AMP_THRESH, color="#e74c3c", lw=2, ls="--", label=f"Threshold = {AMP_THRESH} µV")
    ax1.set_xlabel("Peak-to-peak amplitude (µV)")
    ax1.set_ylabel("Number of epochs")
    ax1.set_title(f"{sid} — Epoch amplitude distribution")
    ax1.legend()

    # kept vs rejected
    kept = np.sum(ptp < AMP_THRESH)
    rejected = np.sum(ptp >= AMP_THRESH)
    ax2.bar(["Kept", "Rejected"], [kept, rejected],
            color=["#2ecc71", "#e74c3c"], edgecolor="white")
    ax2.set_ylabel("Number of epochs")
    ax2.set_title(f"{sid} — Kept: {kept} / Rejected: {rejected}")
    for i, v in enumerate([kept, rejected]):
        ax2.text(i, v + 1, str(v), ha="center", fontweight="bold")

    plt.tight_layout()
    plt.savefig(f"artifact_rejection_{sid}.png", dpi=150, bbox_inches="tight")
    plt.show()
    print(f"Saved: artifact_rejection_{sid}.png")

# P300 is clearest on Cz and P3 across most subjects
# S3 has a weaker P300 compared to others — probably explains the lower accuracy later
for sid in SUBJECTS:
    fs, eeg, trig = load_subject(sid)
    eeg_f = bandpass_filter(eeg, BP_LOW, BP_HIGH, fs)
    onsets, labels = find_trigger_onsets(trig)
    epochs, labels = extract_epochs(eeg_f, onsets, labels, fs, T_START, T_END)
    epochs_ds = resample_epochs(epochs, fs, FS_TARGET)

    n_base = int(BASELINE_S * FS_TARGET)
    baseline = epochs_ds[:, :n_base, :].mean(axis=1, keepdims=True)
    epochs_bl = epochs_ds - baseline

    epochs_clean, labels_clean, _ = reject_artifacts(epochs_bl, labels, AMP_THRESH)
    target_avg = epochs_clean[labels_clean == 1].mean(axis=0)
    nontgt_avg = epochs_clean[labels_clean == -1].mean(axis=0)
    t_ep = np.linspace(T_START, T_END, epochs_bl.shape[1])

    fig, axes = plt.subplots(2, 4, figsize=(16, 8))
    axes = axes.flatten()

    for ch in range(8):
        axes[ch].plot(t_ep, target_avg[:, ch], color="#e74c3c", lw=2, label="Target")
        axes[ch].plot(t_ep, nontgt_avg[:, ch], color="#3498db", lw=2, label="Non-target")
        axes[ch].axvline(0.3, color="gray", ls="--", lw=1)
        axes[ch].set_title(CH_NAMES[ch], fontsize=12, fontweight="bold")
        axes[ch].set_xlabel("Time (s)")
        axes[ch].set_ylabel("µV")
        axes[ch].grid(True, alpha=0.3)
        if ch == 0:
            axes[ch].legend(fontsize=9)

    fig.suptitle(f"{sid} — ERP: Target vs Non-Target", fontsize=14, fontweight="bold")
    plt.tight_layout()
    plt.savefig(f"erp_{sid}.png", dpi=200, bbox_inches="tight")
    plt.show()
    print(f"Saved: erp_{sid}.png")

from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.metrics import balanced_accuracy_score
from pyriemann.estimation import XdawnCovariances
from pyriemann.tangentspace import TangentSpace
from sklearn.decomposition import PCA
from sklearn.utils import resample as sk_resample
from sklearn.ensemble import GradientBoostingClassifier, AdaBoostClassifier, VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

X_DAWN_COMPONENTS = 5 # tested 2,3,4 — 5 gave best results except for S4
SHRINKAGE = 'auto'
cv = StratifiedKFold(n_splits=N_FOLDS, shuffle=True, random_state=42)


def run_subject_classification(epochs, labels, n_comp=4):
    X = np.transpose(epochs, (0, 2, 1))
    y = labels

    skf = StratifiedKFold(n_splits=N_FOLDS, shuffle=True, random_state=42)
    acc_baseline = []
    acc_improved = []

    for train_idx, test_idx in skf.split(X, y):
        X_train, X_test = X[train_idx], X[test_idx]
        y_train, y_test = y[train_idx], y[test_idx]

        xd = XdawnCovariances(nfilter=n_comp, estimator='oas', xdawn_estimator='oas')
        ts = TangentSpace(metric='riemann')

        X_train_cov = xd.fit_transform(X_train, y_train)
        X_test_cov  = xd.transform(X_test)

        X_train_vec = ts.fit_transform(X_train_cov)
        X_test_vec  = ts.transform(X_test_cov)

        # baseline
        clf_base = LinearDiscriminantAnalysis(solver='eigen', shrinkage='auto')
        clf_base.fit(X_train_vec, y_train)
        preds_base = clf_base.predict(X_test_vec)
        acc_baseline.append(balanced_accuracy_score(y_test, preds_base))

        # improve —>>> normalize then PCA then oversample
        scaler = StandardScaler()
        X_train_s = scaler.fit_transform(X_train_vec)
        X_test_s  = scaler.transform(X_test_vec)

        pca = PCA(n_components=0.95)
        X_train_p = pca.fit_transform(X_train_s)
        X_test_p  = pca.transform(X_test_s)  # same transform on test

        X_target    = X_train_p[y_train == 1]
        X_nontarget = X_train_p[y_train == -1]
        y_target    = y_train[y_train == 1]
        y_nontarget = y_train[y_train == -1]

        X_target_up, y_target_up = sk_resample(
            X_target, y_target,
            replace=True,
            n_samples=len(y_nontarget),
            random_state=42
        )

        X_bal = np.vstack((X_nontarget, X_target_up))
        y_bal = np.hstack((y_nontarget, y_target_up))
        perm  = np.random.permutation(len(y_bal))
        X_bal, y_bal = X_bal[perm], y_bal[perm]

        clf_imp = LinearDiscriminantAnalysis(solver='eigen', shrinkage='auto')
        clf_imp.fit(X_bal, y_bal)
        preds_imp = clf_imp.predict(X_test_p)  # X_test_p — same space as X_bal
        acc_improved.append(balanced_accuracy_score(y_test, preds_imp))

    return np.mean(acc_baseline), np.mean(acc_improved)

performance_report = {}

for sid in SUBJECTS:
    fs, eeg, trig = load_subject(sid)
    eeg_f = bandpass_filter(eeg, BP_LOW, BP_HIGH, fs)
    onsets, labels = find_trigger_onsets(trig)
    epochs, labels = extract_epochs(eeg_f, onsets, labels, fs, T_START, T_END)
    epochs_ds = resample_epochs(epochs, fs, FS_TARGET)

    n_base    = int(BASELINE_S * FS_TARGET)
    epochs_bl = epochs_ds - epochs_ds[:, :n_base, :].mean(axis=1, keepdims=True)
    epochs_final, labels_final, _ = reject_artifacts(epochs_bl, labels, AMP_THRESH)
    acc_base, acc_imp = run_subject_classification(
        epochs_final, labels_final, n_comp=X_DAWN_COMPONENTS
    )

    performance_report[sid] = (acc_base, acc_imp)
    print(f"{sid}:")
    print(f"   LDA baseline   = {acc_base:.2%}")
    print(f"   LDA improved   = {acc_imp:.2%}")
    print(f"   Gain           = {(acc_imp - acc_base):.2%}")
    print()

print("SUMMARY:")
for sid, (base, imp) in performance_report.items():
    print(f"{sid}: {base:.2%} → {imp:.2%}  (Δ {(imp-base):.2%})")

classifiers = {
    'LDA':          Pipeline([('scaler', StandardScaler()), ('clf', LinearDiscriminantAnalysis(solver='eigen', shrinkage='auto'))]),
    'SVM':          Pipeline([('scaler', StandardScaler()), ('clf', SVC(kernel='rbf', C=10.0, probability=True, class_weight='balanced'))]),
    'Random Forest':Pipeline([('scaler', StandardScaler()), ('clf', RandomForestClassifier(n_estimators=200, class_weight='balanced', random_state=42))]),
    'Logistic Reg': Pipeline([('scaler', StandardScaler()), ('clf', LogisticRegression(solver='lbfgs', max_iter=1000, class_weight='balanced'))]),
    'Gradient Boost':Pipeline([('scaler', StandardScaler()), ('clf', GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, random_state=42))]),
    'AdaBoost':     Pipeline([('scaler', StandardScaler()), ('clf', AdaBoostClassifier(n_estimators=100, random_state=42))]),
    'Ensemble Vote':Pipeline([('scaler', StandardScaler()), ('clf', VotingClassifier(
                                   estimators=[
                                       ('lda', LinearDiscriminantAnalysis(solver='eigen', shrinkage='auto')),
                                       ('svm', SVC(kernel='rbf', C=10.0, probability=True, class_weight='balanced')),
                                       ('rf',  RandomForestClassifier(n_estimators=200, class_weight='balanced', random_state=42))
                                   ], voting='soft'))]),
}

# KNN and Naive Bayes removed (unperformed)---> they were in previous version

clf_results = {}

for sid in SUBJECTS:
    fs, eeg, trig = load_subject(sid)
    eeg_f = bandpass_filter(eeg, BP_LOW, BP_HIGH, fs)
    onsets, labels = find_trigger_onsets(trig)
    epochs, labels = extract_epochs(eeg_f, onsets, labels, fs, T_START, T_END)
    epochs_ds = resample_epochs(epochs, fs, FS_TARGET)

    n_base    = int(BASELINE_S * FS_TARGET)
    epochs_bl = epochs_ds - epochs_ds[:, :n_base, :].mean(axis=1, keepdims=True)
    epochs_final, labels_final, _ = reject_artifacts(epochs_bl, labels, AMP_THRESH)

    X = np.transpose(epochs_final, (0, 2, 1)).reshape(epochs_final.shape[0], -1)
    y = labels_final

    clf_results[sid] = {}
    print(f"\n{sid}:")
    for name, clf in classifiers.items():
        acc = cross_val_score(clf, X, y, cv=cv, scoring='accuracy').mean()
        auc = cross_val_score(clf, X, y, cv=cv, scoring='roc_auc').mean()
        clf_results[sid][name] = {'acc': acc, 'auc': auc}
        print(f"  {name:15s} Accuracy: {acc:.3f} | AUC: {auc:.3f}")

# Bar chart: baseline vs improved
sids  = list(performance_report.keys())
bases = [performance_report[s][0] * 100 for s in sids]
imps  = [performance_report[s][1] * 100 for s in sids]

x, w = np.arange(len(sids)), 0.35
fig, ax = plt.subplots(figsize=(10, 5))
ax.bar(x - w/2, bases, w, color='#3498db', label='LDA baseline')
ax.bar(x + w/2, imps,  w, color='#e74c3c', label='LDA improved')
ax.set_xticks(x)
ax.set_xticklabels(sids, fontsize=12)
ax.set_ylabel('Balanced Accuracy (%)', fontsize=11)
ax.set_ylim(60, 100)
ax.set_title('Baseline vs Improved LDA — All Subjects', fontsize=13, fontweight='bold')
ax.legend(fontsize=10)
ax.grid(axis='y', alpha=0.3)
for i, (b, m) in enumerate(zip(bases, imps)):
    ax.text(i - w/2, b + 0.3, f'{b:.1f}%', ha='center', fontsize=9)
    ax.text(i + w/2, m + 0.3, f'{m:.1f}%', ha='center', fontsize=9)
plt.tight_layout()
plt.savefig('baseline_vs_improved.png', dpi=150, bbox_inches='tight')
plt.show()

# Heatmap: classifier comparison
clf_names  = list(classifiers.keys())
acc_matrix = np.array([[clf_results[s][n]['acc'] for n in clf_names] for s in sids])
auc_matrix = np.array([[clf_results[s][n]['auc'] for n in clf_names] for s in sids])

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 4))
sns.heatmap(pd.DataFrame(acc_matrix, index=sids, columns=clf_names),
            annot=True, fmt='.3f', cmap='YlOrRd', ax=ax1, vmin=0.8, vmax=1.0)
ax1.set_title('Accuracy', fontsize=12, fontweight='bold')
ax1.set_xticklabels(clf_names, rotation=35, ha='right')

sns.heatmap(pd.DataFrame(auc_matrix, index=sids, columns=clf_names),
            annot=True, fmt='.3f', cmap='YlOrRd', ax=ax2, vmin=0.8, vmax=1.0)
ax2.set_title('AUC-ROC', fontsize=12, fontweight='bold')
ax2.set_xticklabels(clf_names, rotation=35, ha='right')

plt.suptitle('Classifier Comparison — All Subjects', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig('classifier_heatmap.png', dpi=150, bbox_inches='tight')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

subjects = ['S1', 'S2', 'S3', 'S4', 'S5']

paper_acc    = [95.0, 93.0, 90.0, 96.0, 96.0]
our_lda      = [95.2, 93.2, 90.2, 96.6, 95.6]
our_improved = [88.2, 85.9, 78.3, 90.1, 91.1]

x = np.arange(len(subjects))
w = 0.25

fig, ax = plt.subplots(figsize=(12, 6))
ax.bar(x - w,   paper_acc,    w, color='#2c3e50', label='TVLDA Paper (Accuracy)')
ax.bar(x,       our_lda,      w, color='#3498db', label='Our LDA (Accuracy)')
ax.bar(x + w,   our_improved, w, color='#e74c3c', label='Our Improved (Balanced Accuracy)')

ax.set_xticks(x)
ax.set_xticklabels(subjects, fontsize=12)
ax.set_ylabel('%', fontsize=11)
ax.set_ylim(60, 105)
ax.set_title('Our Results vs TVLDA Paper', fontsize=14, fontweight='bold')
ax.legend(fontsize=10)
ax.grid(axis='y', alpha=0.3)

for i in range(len(subjects)):
    ax.text(i - w,   paper_acc[i]    + 0.3, f'{paper_acc[i]:.0f}%',    ha='center', fontsize=8)
    ax.text(i,       our_lda[i]      + 0.3, f'{our_lda[i]:.0f}%',      ha='center', fontsize=8)
    ax.text(i + w,   our_improved[i] + 0.3, f'{our_improved[i]:.0f}%', ha='center', fontsize=8)

plt.tight_layout()
plt.savefig('comparison_paper.png', dpi=200, bbox_inches='tight')
plt.show()
print("Saved: comparison_paper.png")